import React from 'react';
import { Sparkles, BookOpen, Edit3, Globe } from 'lucide-react';
import { useLanguage } from '../../context/LanguageContext';
import type { VietnameseDefinitionProvenance } from '../../types/vocab';

interface ProvenanceBadgeProps {
  provenance?: VietnameseDefinitionProvenance;
  className?: string;
}

export const ProvenanceBadge: React.FC<ProvenanceBadgeProps> = ({ provenance, className = '' }) => {
  const { language, t } = useLanguage();

  if (!provenance || provenance.source === 'unknown') {
    return null;
  }

  if (provenance.isUserEdited || provenance.source === 'user_edit') {
    return (
      <span
        title={
          language === 'vi'
            ? `Định nghĩa do người học tùy chỉnh${provenance.originalSource ? ` (Nguồn gốc: ${provenance.originalSource})` : ''}`
            : `Customized by user${provenance.originalSource ? ` (Original source: ${provenance.originalSource})` : ''}`
        }
        className={`inline-flex items-center gap-1 rounded-full border border-amber-200 bg-amber-50 px-2 py-0.5 text-[11px] font-semibold text-amber-800 dark:border-amber-800/60 dark:bg-amber-950/40 dark:text-amber-300 ${className}`}
      >
        <Edit3 className="h-3 w-3" />
        <span>{t.lookup.userEdited || (language === 'vi' ? 'Đã chỉnh sửa' : 'User edited')}</span>
      </span>
    );
  }

  if (provenance.source === 'ai') {
    const modelDetails = provenance.model
      ? `${provenance.provider || 'AI'}: ${provenance.model}`
      : provenance.provider || 'AI Model';

    return (
      <span
        title={
          language === 'vi'
            ? `Bản dịch ngữ cảnh được tạo bởi mô hình ${modelDetails}`
            : `Contextual translation generated by ${modelDetails}`
        }
        className={`inline-flex items-center gap-1 rounded-full border border-indigo-200/90 bg-indigo-50/90 px-2 py-0.5 text-[11px] font-semibold text-indigo-700 dark:border-indigo-800/80 dark:bg-indigo-950/50 dark:text-indigo-300 ${className}`}
      >
        <Sparkles className="h-3 w-3 text-indigo-500" />
        <span>{t.lookup.aiTranslated || (language === 'vi' ? 'Dịch bằng AI' : 'AI Translation')}</span>
        {provenance.provider && (
          <span className="text-[9px] opacity-75 font-mono hidden sm:inline">
            ({provenance.provider})
          </span>
        )}
      </span>
    );
  }

  if (provenance.source === 'dictionary') {
    return (
      <span
        title={language === 'vi' ? 'Nghĩa được trích xuất từ từ điển' : 'Extracted from dictionary'}
        className={`inline-flex items-center gap-1 rounded-full border border-slate-200 bg-slate-50 px-2 py-0.5 text-[11px] font-semibold text-slate-600 dark:border-slate-800 dark:bg-slate-900/60 dark:text-slate-300 ${className}`}
      >
        <BookOpen className="h-3 w-3 text-slate-400" />
        <span>{t.lookup.dictionarySource || (language === 'vi' ? 'Từ điển' : 'Dictionary')}</span>
      </span>
    );
  }

  if (provenance.source === 'machine') {
    return (
      <span
        title={language === 'vi' ? 'Bản dịch máy tự động' : 'Automated machine translation'}
        className={`inline-flex items-center gap-1 rounded-full border border-cyan-200 bg-cyan-50 px-2 py-0.5 text-[11px] font-semibold text-cyan-800 dark:border-cyan-800/60 dark:bg-cyan-950/40 dark:text-cyan-300 ${className}`}
      >
        <Globe className="h-3 w-3 text-cyan-500" />
        <span>{t.lookup.machineTranslated || (language === 'vi' ? 'Dịch máy' : 'Machine translated')}</span>
      </span>
    );
  }

  return null;
};
